CREATE DATABASE RFM_SALES;

USE RFM_SALES;

SELECT Top 10
* 
FROM SAMPLE_SALES_DATA;

Select Count(*),
Count(DISTINCT ORDERNUMBER) 
From SAMPLE_SALES_DATA;

SELECT
	ORDERNUMBER,
	ORDERLINENUMBER,
	SAMPLE_SALES_DATA.*
FROM SAMPLE_SALES_DATA
ORDER BY 1,2;

SELECT
	COUNT( DISTINCT ORDERNUMBER) AS NO_OF_ORDERS,
	SUM(QUANTITYORDERED) AS QTY_ORDERED,
	SUM(QUANTITYORDERED)/COUNT( DISTINCT ORDERNUMBER) AS AVG_BASKET_SIZE
FROM SAMPLE_SALES_DATA;

SELECT
	YEAR_ID AS YEAR,
	MONTH_ID AS MONTH,
	COUNT( DISTINCT ORDERNUMBER) AS NO_OF_ORDERS,
	SUM(QUANTITYORDERED) AS QTY_ORDERED,
	SUM(QUANTITYORDERED)/COUNT( DISTINCT ORDERNUMBER) AS AVG_BASKET_SIZE
FROM SAMPLE_SALES_DATA
GROUP BY YEAR_ID, MONTH_ID
ORDER BY YEAR_ID, MONTH_ID;


-- Now, pivoting the result using CASE WHEN

SELECT
	MONTH_ID AS MONTH,
	COUNT(DISTINCT CASE WHEN YEAR_ID = 2003 THEN ORDERNUMBER ELSE NULL END) AS NUMBER_OF_ORDERS_2003,
	COUNT(DISTINCT CASE WHEN YEAR_ID = 2004 THEN ORDERNUMBER ELSE NULL END) AS NUMBER_OF_ORDERS_2004,
	COUNT(DISTINCT CASE WHEN YEAR_ID = 2005 THEN ORDERNUMBER ELSE NULL END) AS NUMBER_OF_ORDERS_2005
	FROM SAMPLE_SALES_DATA
GROUP BY MONTH_ID
ORDER BY MONTH_ID;

SELECT
	MONTH_ID AS MONTH,
	COUNT(DISTINCT CASE WHEN YEAR_ID = 2003 THEN QUANTITYORDERED ELSE NULL END) AS QTY_ORDERED_2003,
	COUNT(DISTINCT CASE WHEN YEAR_ID = 2004 THEN QUANTITYORDERED ELSE NULL END) AS QTY_ORDERED_2004,
	COUNT(DISTINCT CASE WHEN YEAR_ID = 2005 THEN QUANTITYORDERED ELSE NULL END) AS QTY_ORDERED_2005
	FROM SAMPLE_SALES_DATA
GROUP BY MONTH_ID
ORDER BY MONTH_ID;

