USE RFM;

SELECT *
FROM SAMPLE_SALES_DATA
LIMIT 10;

## FINDING NUMBER OF CUSTOMERS, ORDERS, QTY AND SALES

SELECT 
COUNT(DISTINCT CUSTOMERNAME) AS NO_OF_CUSTOMERS,
COUNT(DISTINCT ORDERNUMBER) AS NO_OF_ORDERS,
SUM(QUANTITYORDERED) AS ORDER_QTY,
ROUND(SUM(SALES),0) AS TOTAL_SALES
FROM SAMPLE_SALES_DATA;

##  NUMBER OF ORDERS PER DATE
SELECT 
	ORDERDATE,
	COUNT(ORDERNUMBER) AS NO_OF_ORDERS
FROM SAMPLE_SALES_DATA
GROUP BY 1
ORDER BY 2 DESC;

##  QUANTITIES ORDERED PER DATE
SELECT 
	ORDERDATE,
	SUM(QUANTITYORDERED) AS ORDERS_QTY
FROM SAMPLE_SALES_DATA
GROUP BY 1
ORDER BY 2 DESC;

## HIHGHEST REVENUE MADE THROUGHOUT THE DAY
SELECT 
	ORDERDATE,
	SUM(SALES) AS TOTAL_SALES_PER_DATE
FROM SAMPLE_SALES_DATA
GROUP BY 1
ORDER BY 2 DESC;

## TOP 5 HIGHEST PAID CUSTOMERS
SELECT
	CUSTOMERNAME,
	ORDERDATE,
	SUM(SALES) TOTAL_SALES
FROM SAMPLE_SALES_DATA
GROUP BY 1, 2
ORDER BY 2
LIMIT 5;

## RFM SEGMENTATION:

CREATE OR REPLACE VIEW RFM AS
WITH SUMMARY_TABLE AS
(SELECT
CUSTOMERNAME,
	DATEDIFF((SELECT MAX(ORDERDATE) FROM SAMPLE_SALES_DATA), MAX(ORDERDATE)) AS RECENCY_VALUE,
	COUNT(DISTINCT ORDERNUMBER) AS FREQUENCY_VALUE,
	ROUND(SUM(SALES),0) AS MONETARY_VALUE
FROM SAMPLE_SALES_DATA
GROUP BY 1),

RFM_SCORE AS(
SELECT
	SUMMARY_TABLE.*,
    NTILE(5) OVER(ORDER BY RECENCY_VALUE DESC) AS R_SCORE,
    NTILE(5) OVER(ORDER BY FREQUENCY_VALUE ASC) AS F_SCORE,
	NTILE(5) OVER(ORDER BY MONETARY_VALUE ASC) AS M_SCORE 
FROM SUMMARY_TABLE) ,

RFM_COMBINATION AS(
SELECT
	RFM_SCORE.*,
	(R_SCORE+ F_SCORE+ M_SCORE) AS TOTAL_RFM_SCORE,
	CONCAT_WS('', R_SCORE, F_SCORE, M_SCORE) AS RFM_COMBINATION_SCORE
FROM RFM_SCORE)

SELECT
	CUSTOMERNAME,
	R_SCORE AS RECENCY, F_SCORE AS FREQUENCY, M_SCORE AS MONETARY,
	CASE 
		WHEN TOTAL_RFM_SCORE =15 THEN 'CHAMPIONS'
		WHEN TOTAL_RFM_SCORE >=12 THEN 'LOYAL_CUSTOMERS'
		WHEN TOTAL_RFM_SCORE BETWEEN 9 AND 11 THEN 'POTENTIAL_LOYALISTS'
		WHEN TOTAL_RFM_SCORE BETWEEN 6 AND 8 THEN 'PROMISING_CUSTOMERS'
		WHEN TOTAL_RFM_SCORE BETWEEN 4 AND 5 THEN 'HIBERNATING'
		WHEN TOTAL_RFM_SCORE <=3 THEN 'LOST'
		ELSE 'OTHERS'
END AS CUSTOMER_SEGMENT
FROM RFM_COMBINATION;


SELECT * FROM RFM;














